package jp.ac.it_college.std.s22016.weather__app

data class City(
    val name: String,
    val q: String
)

val cityList = listOf(
    City("北 海 道 (札 幌)","Sapporo"),
    City("青  森","Aomori"),
    City("岩  手 (盛 岡)","Morioka"),
    City("宮  城 (仙 台)","Morioka"),
    City("秋  田","Akita"),
    City("山  形","Yamagata"),
    City("福  島","Hukushima"),
    City("茨  城 (水 戸)","Mito"),
    City("栃  木 (宇 都 宮)","Utsunomiya"),
    City("群  馬 (前 橋)","Maehashi"),
    City("埼  玉 (さ い た ま)","Saitama"),
    City("千  葉","Chiba"),
    City("東  京","Tokyo"),
    City("神 奈 川 (横 浜)","Yokohama"),
    City("新  潟","Nigata"),
    City("富  山","Toyama"),
    City("石 川 (金 沢)","Kanazawa"),
    City("福  井","Hukui"),
    City("山  梨 (甲 府)","Kohu"),
    City("長  野","Nagano"),
    City("岐  阜","Gihu"),
    City("静  岡","Shizuoka"),
    City("愛  知 (名 古 屋)","Nagoya"),
    City("三  重 (津)","Tsu"),
    City("滋  賀 (大 津)","Otsu"),
    City("京  都","Kyoto"),
    City("大  阪","Osaka"),
    City("兵  庫","Hyogo"),
    City("奈  良","Nara"),
    City("和 歌 山","Wakayama"),
    City("鳥  取","Tottori"),
    City("島  根 (松 江)","Matsue"),
    City("岡  山","Okayama"),
    City("広  島","Hiroshima"),
    City("山  口","Yamaguti"),
    City("徳  島","Tokushima"),
    City("香  川 (高 松)","Takamatsu"),
    City("愛  媛 (松 山)","Matsuyama"),
    City("高  知","Koti"),
    City("福  岡","Hukuoka"),
    City("佐  賀","Saga"),
    City("長  崎","Nagasaki"),
    City("熊  本","Kumamoto"),
    City("大  分","Oita"),
    City("宮  崎","Miyazaki"),
    City("鹿 児 島","Kagoshima"),
    City("沖  縄 (那 覇)","Naha")
)